server:
  port: 8080 # default

spring:
  output:
    ansi:
      enabled: always # log color

  jpa:
    hibernate:
      ddl-auto: update # create: ??? ? ??? ??? ?? ?? / update: ??
    show-sql: false # JPA? ????? sql? log? ??. hibernate log ?? ? false? ??
    properties:
      hibernate:
        ### sql ??? ??
        format_sql: true # sql ??? (? ??, ????)
        highlight_sql: true # sql ???? ????? ??
        use_sql_comments: true # sql ??
        default_batch_fetch_size: 10
        dialect: org.hibernate.dialect.MySQLDialect # JPA? ???? sql? mysql? ??

  datasource:
    url: jdbc:mysql://localhost:3306/sbb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password:

logging:
  level:
    org.hibernate.SQL: DEBUG # hibernate sql log level
    org.hibernate.orm.jdbc.bind: TRACE # ???? ???? ?? ??
    org.hibernate.orm.jdbc.extract: TRACE # ??? ??? ? ??
    org.springframework.transaction.interceptor: TRACE # ???? ??? ??? ?? ??
