server:
  port: 8080 # default
  shutdown: graceful

cors:
  allowed-origins: "http://localhost:5173"

spring:
  output:
    ansi:
      enabled: always # log color

  jpa:
    hibernate:
      ddl-auto: update # create: 재시작 시 테이블 지우고 다시 만듦 / update: 유지
    show-sql: false # JPA가 create 해주는 sql을 log로 남김. hibernate log 사용 시 false로 설정
    properties:
      hibernate:
        ### sql 가독성 증가
        format_sql: true # sql 포매팅 (줄 바꿈, 들여쓰기)
        highlight_sql: true # sql 키워드에 하이라이트 표시
        use_sql_comments: true # sql 주석
        default_batch_fetch_size: 10
        dialect: org.hibernate.dialect.MySQLDialect # JPA가 사용하는 sql을 mysql로 설정

  datasource:
    url: jdbc:mysql://localhost:3307/sbb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password:
    hikari:
      auto-commit: false

logging:
  level:
    org.hibernate.SQL: DEBUG # hibernate sql log level
    org.hibernate.orm.jdbc.bind: TRACE # 바인딩된 파라미터 값을 출력
    org.hibernate.orm.jdbc.extract: TRACE # 쿼리로 읽어온 값 출력
    org.springframework.transaction.interceptor: TRACE # 트랜잭션 관리와 관련된 동작 출력
